package vue;
import static dao.EchecsDao.position;
import java.util.ArrayList;
import elo.*;
import dao.*;

public class FrmMain extends java.awt.Frame {
private static ArrayList lst = new ArrayList();
    public FrmMain() {
        initComponents();
        lst = dao.EchecsDao.readEchec();
        for (int i=0; i<lst.size();i++) {
            Joueur joueur = (Joueur)lst.get(i);
            String jr = joueur.toString();
            lstJoueurs.add(jr);
        }
        btnSupprimer.enable(false);
    }
    
        public void fermer() {
            FileRead file = new FileRead();
        dispose();
        String[] str = new String[lst.size()];
        for(int i=0;i<lst.size();i++){
            Joueur joueur = (Joueur)lst.get(i);
            str[i]=joueur.toText();
        }
       file.WriteFile(str);
        }
    
    	public void retourne(Joueur joueur) {
	/* Méthode publique implantant le traitement à faire, appelée par la fenêtre secondaire :
		- on peut recevoir des valeurs de la fenêtre secondaire
		- on effectue les traitements dans la fenêtre principale (affichage de la valeur reçue) */
		int pos = dao.EchecsDao.position(joueur);
                String jr = joueur.toString();
                lstJoueurs.add(jr,pos);
                lst.add(pos,joueur);
                
                
	}
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJoueurs = new java.awt.Label();
        lstJoueurs = new java.awt.List();
        btnNouveau = new java.awt.Button();
        btnSupprimer = new java.awt.Button();
        btnFermer = new java.awt.Button();

        setTitle("Classement Elo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblJoueurs.setText("Joueurs");

        lstJoueurs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstJoueursItemStateChanged(evt);
            }
        });

        btnNouveau.setLabel("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        btnSupprimer.setLabel("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnFermer.setLabel("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btnFermer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJoueurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstJoueurs, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJoueurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lstJoueurs, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNouveau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFermer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        fermer();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
        // TODO add your handling code here:
        FrmNouveau f = FrmNouveau.getInstance(this);
		f.setVisible(true);
		f.setExtendedState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        int pos = lstJoueurs.getSelectedIndex();
        lstJoueurs.remove(pos);
        lst.remove(pos);
        btnSupprimer.enable(false);
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void lstJoueursItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstJoueursItemStateChanged
        // TODO add your handling code here:
        if (lstJoueurs.getSelectedIndex()>=0 ) {btnSupprimer.enable(true);}
        else {btnSupprimer.enable(false);}
    }//GEN-LAST:event_lstJoueursItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        fermer();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        fermer();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnFermer;
    private java.awt.Button btnNouveau;
    private java.awt.Button btnSupprimer;
    private java.awt.Label lblJoueurs;
    private java.awt.List lstJoueurs;
    // End of variables declaration//GEN-END:variables
}